"""
Defines Configuration class for representation of molecular
structure at one particular point in time.

Part of raman package.

Copyright Sean McGrath 2015. Issued under the MIT License.
"""

from .spectrum import Spectrum
from .matrix import DistanceMatrix


class Configuration:
    """
    A single molecular Configuration - associates a Spectrum
    and a DistanceMatrix at a single point in time and temperature.
    """

    def __init__(self, spectrum, matrix, time=None, temperature=None):
        """
        Constructor.
        :param spectrum: a raman.Spectrum
        :param matrix: a raman.DistanceMatrix
        :param time: a string describing the time the Configuration was captured.
        :param temperature: the temperature of the Configuration.
        """

        self.spectrum = spectrum
        self.matrix = matrix
        self.time = time
        self.temperature = temperature

    def __len__(self):
        return len(self.matrix)

    def __str__(self):
        string = 'Configuration with {} atoms'.format(len(self))
        if self.temperature:
            string += ' at {}'.format(self.temperature)
        if self.time:
            string += ' at {}'.format(self.time)
        return string

    @staticmethod
    def from_log_file(filename, time=None, temp=None):
        """
        Create a Configuration from the information
        in a Gaussian .log file.
        :param filename: path to a .log file generated by Gaussian.
        """

        spectrum = Spectrum.from_log_file(filename)
        matrix = DistanceMatrix.from_log_file(filename)

        return Configuration(spectrum, matrix, time, temp)
